[project]
description = "Python static command parser. Like argparse, but without connection to CLI."
name = "statikomand"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
